### PR TITLE
Fix libusb-1.0.22 deprecated libusb_set_debug with libusb_set_option

### PR DESCRIPTION
**Pull request by evan-goode**
See https://www.mail-archive.com/qemu-devel@nongnu.org/msg525728.html

### CODE REVIEW

**Comment by evan-goode** [comment]
Qemu would not compile on my system without this patch.

**Comment by kholia** [comment]
Thanks! I need to rebase this branch but I don't have a suitable system to test this stuff.

**Comment by sersoong** [comment]
Confirmed,and Tested,it works fine on my archlinux.

**Comment by evan-goode** [comment]
It seems like this PR may no longer be necessary. kholia/qemu still doesn't build on latest Arch, thanks to a completely new deprecation (https://bugs.launchpad.net/qemu/+bug/1794939), but vanilla QEMU works fine as long as it's new enough, right?

**Comment by kholia** [comment]
Yes, use vanilla QEMU, if it works.

**Pull request closed without merging**
